all:
	mkdir ../out
	g++ ftrue.cpp -o ../out/ftrue -std="c++17"
	g++ ffalse.cpp -o ../out/ffalse -std="c++17"
	g++ frm.cpp -o ../out/frm -std="c++17"
	g++ ftouch.cpp -o ../out/ftouch -std="c++17"
	g++ fecho.cpp -o ../out/fecho -std="c++17"
	g++ fyes.cpp -o ../out/fyes -std="c++17"
	g++ fcat.cpp -o ../out/fcat -std="c++17"
	g++ fls.cpp -o ../out/fls -std=c++17 -lstdc++fs
	
	./ftouch test
	./frm test

	./fecho owo
	- timeout 1 ./fyes uwu
	echo "No errors found."
